services:
  - type: web
    name: ordenya-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: OrdenYa
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: APP_LOCALE
        value: es
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: warning
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: BROADCAST_CONNECTION
        value: log
      - key: FRONTEND_URL
        sync: false
      - key: SANCTUM_STATEFUL_DOMAINS
        sync: false
      - key: BCRYPT_ROUNDS
        value: "12"
